// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hhbxmvnlocwxhcddbfws.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhoYnhtdm5sb2N3eGhjZGRiZndzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwNTY2NDcsImV4cCI6MjA3MTYzMjY0N30.Ce7XlijnSQ0bSJF3A_a7IyZoE-rdWR4bVemHSFiFA_Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});