name: Build macOS App

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-mac:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build web app
      run: npm run build
      
    - name: Setup iOS (for macOS)
      run: |
        npx cap add ios || true
        npx cap sync ios
        
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Build iOS project for Mac
      run: |
        cd ios/App
        xcodebuild -workspace App.xcworkspace \
                   -scheme App \
                   -destination 'platform=macOS,arch=x86_64' \
                   -configuration Release \
                   clean build \
                   CODE_SIGN_IDENTITY="" \
                   CODE_SIGNING_REQUIRED=NO
                   
    - name: Create DMG installer
      run: |
        # יצירת DMG עם האפליקציה
        mkdir -p dist-mac
        cp -R ios/App/build/Release-maccatalyst/App.app dist-mac/
        hdiutil create -volname "מערכת ניהול פרויקטים Pro" \
                       -srcfolder dist-mac \
                       -ov -format UDZO \
                       ProjectManager-macOS.dmg
                       
    - name: Upload DMG
      uses: actions/upload-artifact@v4
      with:
        name: ProjectManager-macOS
        path: ProjectManager-macOS.dmg
        retention-days: 30
        
    - name: Create Release
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.run_number }}
        name: מערכת ניהול פרויקטים Pro v${{ github.run_number }}
        body: |
          ## מערכת ניהול פרויקטים Pro - גירסה למק
          
          ### הורדה והתקנה:
          1. הורד את קובץ ה-DMG
          2. פתח את הקובץ ולחץ על האפליקציה
          3. גרור את האפליקציה לתיקיית Applications
          4. הפעל את האפליקציה
          
          ### תכונות בגירסה זו:
          - ממשק עברי מלא עם תמיכה RTL
          - פתיחת תיקיות ישירה ב-Finder
          - שמירת נתונים מקומית בטוחה
          - אופטימיזציות ביצועים מתקדמות
          - תמיכה בלוגו מותאם אישית
          
          ### דרישות מערכת:
          - macOS 11.0 (Big Sur) ואילך
          - 4GB זכרון פנוי
          - 1GB שטח דיסק פנוי
        files: ProjectManager-macOS.dmg
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}